# - id: doi:10.1371/journal.pcbi.1007128
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2

# - id: doi:10.1016/j.csbj.2020.05.017
#   image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

# - id: doi:10.7554/eLife.32822
#   image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: doi:10.3390/nu13093248
  image: https://cdn.ncbi.nlm.nih.gov/pmc/blobs/085f/8471894/439e880a085a/nutrients-13-03248-g001.jpg
  
- id: doi:10.1016/j.ijpddr.2025.100588
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2211320725000119-ga1.jpg

- id: doi:10.1159/000546100
  image: https://karger.silverchair-cdn.com/karger/content_public/journal/lfg/18/1/10.1159_000546100/1/m_000546100_ga.jpeg?Expires=1756687471&Signature=l01VEIYJjL18Y8e7pZgpKKqXTPueiN2z5IrF9OSa40eFDME1Du2WpyLXwvMLJ-nqylyQKlntqNM~XDbavPUzvHjZyFVyCSBtlidVLuGxjIx6r2kSbirR4CwBXOZ5g64XuaIVc-0krKyMUEeV1U3mAqxoyuuKG32mqbgWvQhirZgPPwHh913q-2g45hOp7RMEIZ6mbUPid9cGvPZwQ3oKyKPyImBnYCZ4qanEt7RFT5qm7IDFbbZbl2moqzVlAqcmJomJNneC45GnocBjaeL5VP6cmPwjW0BYCLtpxVOkXVVLj9E-NmqBhwg8719wkgkxp0IhZGpQSysCQUoRRmGBJQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1101/2024.03.20.585968
  image: https://www.biorxiv.org/content/biorxiv/early/2024/08/15/2024.03.20.585968/F1.medium.gif

- id: doi:10.1681/ASN.0000000688
  image: https://images.journals.lww.com/jasn/GAPreview.00001751-202508000-00008.ga.jpeg