name: update-network
run-name: update network graph

on:
  # run when called from another workflow
  workflow_call:
    outputs:
      changed:
        value: ${{ jobs.update-network.outputs.changed }}

  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  FORCE_COLOR: true

jobs:
  update-network:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Debug dump
        uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout branch contents
        if: github.event.action != 'closed'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Set up Python
        if: github.event.action != 'closed'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python packages for network generation
        if: github.event.action != 'closed'
        run: |
          python -m pip install --upgrade webweb pyyaml python-frontmatter

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Regenerate network graph
        if: github.event.action != 'closed'
        run: python web.py
        timeout-minutes: 5

      - name: Check if network graph changed
        if: github.event.action != 'closed'
        id: changed
        uses: tj-actions/verify-changed-files@v18
        with:
          files: |
            _data/webweb.json

      - name: Commit updated network graph to branch
        if: |
          github.event.action != 'closed' &&
          steps.changed.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update network graph"
          file_pattern: "_data/webweb.json"

    outputs:
      changed: ${{ steps.changed.outputs.files_changed || false }}